name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - add-actions

jobs:
  check:
    name: WP Plugin Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Rename plugin directory
        run: |
          mv ./trunk ${{ runner.temp }}/embed-consent

      - name: Run plugin check
        uses: wordpress/plugin-check-action@v1
        with:
          build-dir: ${{ runner.temp }}/embed-consent
